from datetime import date, datetime, timezone

from sqlalchemy import Date, DateTime, Float, ForeignKey, Integer, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


class Forecast(Base):
    """Cached forecast results generated by the ML pipeline."""
    __tablename__ = "forecasts"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    user_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    category_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("product_categories.id", ondelete="CASCADE"), nullable=False
    )
    forecast_type: Mapped[str] = mapped_column(
        String(30), nullable=False, default="individual",
        comment="individual | cluster_fallback"
    )
    period_start: Mapped[date] = mapped_column(Date, nullable=False)
    period_end: Mapped[date] = mapped_column(Date, nullable=False)
    predicted_demand_index: Mapped[float] = mapped_column(Float, nullable=False)
    confidence_score: Mapped[float] = mapped_column(Float, nullable=False)
    confidence_label: Mapped[str] = mapped_column(
        String(15), nullable=False, default="Medium",
        comment="High | Medium | Low"
    )
    explanation_text: Mapped[str | None] = mapped_column(String(500), nullable=True)
    model_version: Mapped[str] = mapped_column(String(40), nullable=False, default="1.0.0")
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )

    # Relationships
    user: Mapped["User"] = relationship("User")
    category: Mapped["ProductCategory"] = relationship("ProductCategory")

    def __repr__(self) -> str:
        return f"<Forecast id={self.id} user={self.user_id} category={self.category_id} pred={self.predicted_demand_index}>"


class ProductionPlan(Base):
    """Suggested and accepted production plans informed by forecasts."""
    __tablename__ = "production_plans"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    user_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    forecast_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("forecasts.id", ondelete="SET NULL"), nullable=True
    )
    category_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("product_categories.id", ondelete="CASCADE"), nullable=False
    )
    suggested_quantity: Mapped[int] = mapped_column(Integer, nullable=False)
    accepted_quantity: Mapped[int | None] = mapped_column(Integer, nullable=True)
    plan_period_start: Mapped[date] = mapped_column(Date, nullable=False)
    plan_period_end: Mapped[date] = mapped_column(Date, nullable=False)
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default="suggested",
        comment="suggested | accepted | adjusted | completed"
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )

    # Relationships
    user: Mapped["User"] = relationship("User")
    category: Mapped["ProductCategory"] = relationship("ProductCategory")
    forecast: Mapped["Forecast | None"] = relationship("Forecast")

    def __repr__(self) -> str:
        return f"<ProductionPlan id={self.id} user={self.user_id} suggested={self.suggested_quantity}>"
